server:
  port: 8080
#  servlet:
#    context-path: /sell

# mysql是本地地址，redis是外网地址(根据自己需要改)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: passok
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 120.79.213.144
    port: 6379

#公众账号使用的是测试账号，其他账号没有
wechat:
  mpAppId: wx33d635b7420ab51c
  mpAppSecret: aa418fc4932f29ee839290cca7f7b4ed
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
  templateId:
    orderStatus: grymnyvsVIEeT7Z8_vMN9qEjm-Vw97tEdncf4YOy8BY

#此处的域名使用的是内网穿透的域名
projectUrlConfig:
  wechatMpAuthorize: http://freesaber.natapp1.cc
  wechatOpenAuthorize: http://freesaber.natapp1.cc
  sell: http://freesaber.natapp1.cc
  websocket: ws://freesaber.natapp1.cc