server:
  port: 8080
#  servlet:
#    context-path: /sell

# mysql和redis都是docker地址
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.7:3306/sell?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123@abc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 172.17.0.9
    port: 6379

#公众账号使用的是测试账号，其他账号没有
wechat:
  mpAppId: wx33d635b7420ab51c
  mpAppSecret: aa418fc4932f29ee839290cca7f7b4ed
  openAppId:
  openAppSecret:
  mchId: 
  mchKey: 
  keyPath: 
  notifyUrl:
  templateId:
    orderStatus: grymnyvsVIEeT7Z8_vMN9qEjm-Vw97tEdncf4YOy8BY

#此处的域名是生产环境域名
projectUrlConfig:
  wechatMpAuthorize: http://liaosxsell.freesaber.cn
  wechatOpenAuthorize: http://liaosxsell.freesaber.cn
  sell: http://liaosxsell.freesaber.cn
  websocket: ws://liaosxsell.freesaber.cn