server:
  port: 8080
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.7:3306/sell?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123@abc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

wechat:
  mpAppId: wx84b7bc665de827d4
  mpAppSecret: 4e0abdb6401752f95c22de205aa7f2b4